apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: client
build:
  artifacts:
    - image: stephengrider/posts
      context: client
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/posts-depl.yaml
    - infra/k8s/posts.yaml
